name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: DownloadSecureFile@1
      displayName:  Download THNETII.Octokit.Test AuthSecrets
      inputs:
        secureFile: AuthSecrets.json
    - task: CopyFiles@2
      displayName:  Copy THNETII.Octokit.Test AuthSecrets to test directory
      inputs:
        sourceFolder: $(Agent.TempDirectory)
        contents:     AuthSecrets.json
        targetFolder: $(Build.SourcesDirectory)/test/THNETII.Octokit.Test/Authentication.Test/
        overWrite:    true
