name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
variables:
  - group: thnetii.octokit.net-extensions
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - script: |
        dotnet user-secrets set -p test/THNETII.Octokit.Test "Octokit:Credentials:AuthenticationType" "$(Octokit.Credentials.AuthenticationType)"
        dotnet user-secrets set -p test/THNETII.Octokit.Test "Octokit:Credentials:Token" "$(Octokit.Credentials.Token)"
      displayName: dotnet user-secrets set -p test/THNETII.Octokit.Test
    poststeps:
    - script: |
        dotnet user-secrets clear -p test/THNETII.Octokit.Test
      displayName: dotnet user-secrets clear -p test/THNETII.Octokit.Test
      condition: always()
